# Generated by Django 4.2.13 on 2024-06-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_category_icons_alter_server_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="icons",
            new_name="icon",
        ),
    ]
