# Generated by Django 4.2.13 on 2024-09-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chating", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Converstion",
            new_name="Conversation",
        ),
        migrations.RenameField(
            model_name="messages",
            old_name="Converstion",
            new_name="Conversation",
        ),
    ]
