# Generated by Django 4.2.13 on 2024-09-02 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chating", "0002_rename_converstion_conversation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="messages",
            old_name="Conversation",
            new_name="conversation",
        ),
    ]
